name = "ossreleasefeed-worker"
main = "src/index.ts"
compatibility_date = "2026-07-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
APP_NAME = "ossreleasefeed"

[ai]
binding = "AI"
remote = true

[[flagship]]
binding = "FLAGS"
app_id = "eabc32c1-78e1-4148-8e00-0be4fd5cb1ed"
remote = true

[[ratelimits]]
name = "ASSISTANT_CLIENT_RATE_LIMITER"
namespace_id = "762019481"

[ratelimits.simple]
limit = 5
period = 60

[[ratelimits]]
name = "ASSISTANT_NETWORK_RATE_LIMITER"
namespace_id = "762019482"

[ratelimits.simple]
limit = 15
period = 60
